#! /bin/sh

killall -q polybar 
killall -q conky
killall -q dunst
# killall -q picom

# Settings {{{
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config automatic_scheme alternate
bspc config window_gap				10
bspc config	padding					20
bspc config split_ratio				0.50
bspc config single_monocle			true
bspc config gapless_monocle			false
bspc config borderless_monocle		false

# }}}

# Rules {{{
# Desktops 1-5 are for terminals only
# I might have to consider adding 'follow=on' to a couple other rules
# Desktop 7 is for pdf viewing/books/documentation
bspc rule -a Zathura desktop='^7' state=tiled
# Desktop 8 is multimedia
bspc rule -a mpv desktop='^8' state=fullscreen
bspc rule -a cantata desktop='^8' state=tiled
bspc rule -a Pavucontrol desktop='^8' state=tiled
# Desktop 9 is for graphic design
bspc rule -a StarUML desktop='^9' state=fullscreen
bspc rule -a Inkscape desktop='^9' state=fullscreen
bspc rule -a Gimp desktop='^9' state=fullscreen
# Desktop 10 is for my browser (unless explicitly moved to another desktop)
bspc rule -a "Brave-browser" desktop='^10' follow=on
bspc rule -a "KeePassXC" desktop='^10' follow=on
# }}}

# Initialization {{{
# Don't you ever think about moving sxhkd below that line
sxhkd & > ~/.sxhkd.log 2>&1
picom -b --experimental-backends & 
# Not really sure why I have kept this one, it doesn't change anything
#$XDG_CONFIG_HOME/scripts/zathura/genwalza
wal -i $HOME/pictures/wallpapers
$XDG_CONFIG_HOME/polybar/launch.sh vita
[ ! -s ~/.config/mpd/mpd.pid ] && mpd &
conky &
dunst &
safeeyes --enable &
# }}}
