;; As designed by Lamprinos Chatziioannou
;; This was designed with the following in mind:
;	1) Easily modifiable to our colorlpapers`signed with the following in mind:
;	2) Minimalistic, not too vibrant
;	3) Elegant

[color]

background = #aa2b2836
foreground = #f4e7c5
foreground-alt = #aaa189
module-fg = #F5F5F5
primary = #E89681
secondary = #F19586
alternate = #D09C99

; Used almost everywhere in the theme (outside of module icons and underlining)
[std]
bg				=	${color.background}	
fg				=	${color.foreground}

; Only responsible for icon and underlining color
[moducolors]

; Essentially colorless
date			= 	${color.alternate}
keyboard		= 	${color.alternate}

; Accent colors
filesystem		=   ${color.module-fg}
mpd				=	${color.module-fg}
memory			=	${color.module-fg}
cpu				=	${color.module-fg}

; Bspwm
bspwm_empty 	= 	${color.foreground}
bspwm_occupied 	= 	${color.secondary} 
bspwm_focused 	= 	${color.primary}
bspwm_focused_b	=	${color.background}
bspwm_urgent	=	${color.alternate}
bspwm_separator	= 	${color.foreground-alt}

; Pulse
pulseaudio		=   ${color.alternate}
pulseaudio_mf	=   ${color.secondary}
pulseaudio_mb	=   ${color.secondary}
