;; As organized by Lamprinos Chatziioannou

; desktops {{{
[module/desktops]
type 					= internal/bspwm
inline-mode				= true
pin-workspaces 			= true
enable-click 			= true
enable-scroll 			= true

;label-focused = 
label-focused 				= 
label-occupied 				= 
label-urgent 				= 
label-empty	 				= 

label-focused-padding		= ${layout.bspwm-padding}
label-empty-padding			= ${layout.bspwm-padding}
label-occupied-padding		= ${layout.bspwm-padding}
label-urgent-padding		= ${layout.bspwm-padding}

; Available tokens:
; name, icon, index
label-focused-foreground 	= ${moducolors.bspwm_focused}
label-focused-background	= ${moducolors.bspwm_focused_b}
label-empty-foreground 		= ${moducolors.bspwm_empty}
label-occupied-foreground 	= ${moducolors.bspwm_occupied}
label-urgent-foreground		= ${moducolors.bspwm_urgent}


;; }}}

; cpu{{{
[module/cpu]
type = internal/cpu
format-prefix = 
format-padding = ${layout.module-padding}
interval = 1

; Available tags: label, bar-load, ramp-load, ramp-coreload
format = <label> 
; Available tokens:  percentage, percentage-sum, percentage-cores, percentage-core[1-9]
label = " %percentage%%"

;colors
format-prefix-foreground 	= ${moducolors.cpu}
format-underline			= ${moducolors.cpu}

; }}}

; date{{{
[module/date]
type = internal/date
interval = 1.0
; See "http://en.cppreference.com/w/cpp/io/manip/put_time" for details on how to format the date string
time = " %I:%M %p"
time-alt =  %Y-%m-%d%
date= " %a %e-%b"
format = <label>
;format-prefix = 
format-padding = ${layout.module-padding}
; Available tokens: date, time
label = %time%


format-prefix-foreground = ${moducolors.date}
; format-underline			= ${moducolors.date}
; }}}

; fs{{{
[module/filesystem]
type = internal/fs
mount-0 = /
mount-1 = /media/terastios
mount-2 = /media/empistos
spacing = 1
interval = 300
fixed-values = true
format-mounted-padding = 1
format-unmounted-padding = ${layout.module-padding}

;icons
format-mounted-prefix = 
format-unmounted-prefix = 
format-mounted-prefix-foreground = ${moducolors.filesystem}
format-mounted-underline = ${moducolors.filesystem}
;format-unmounted-background = ${gruv.focusedbd}

; Available tags: label-mounted, bar-free, bar-used, ramp-capacity
format-mounted = <label-mounted>
format-unmounted = <label-unmounted>

; Available tokens: mountpoint, type, fsname, percentage_{free,used}, total, free, used
label-mounted = " %mountpoint% %percentage_used%%"
label-unmounted =
; }}}

; memory{{{
[module/memory]
type = internal/memory
; Seconds to sleep between updates
; Default: 1
interval = 1
; Available tags: label, {ramp,bar}-{used,free}, {bar,ramp}-swap-{used,free}
format = <label> 
format-prefix = 
format-prefix-foreground = ${moducolors.memory}
format-underline = ${moducolors.memory}
format-padding = ${layout.module-padding}
; Available tokens: percentage_{used,free,swaped_used,swaped_free}, gb_{used,free,total}, mb_{used,free,total}
label = " %percentage_used%%"
; }}}

; mpd {{{
[module/mpd]
type 						=	 internal/mpd
host 						=	 localhost
port 						=	 6600
;password 					=	 hellandfire
interval 					=	 1

format-online-prefix		= 	 
format-online-prefix-padding-right = 2;
format-online 				=	 <icon-prev> <label-song> <icon-next>
format-online-foreground 	=	 ${moducolors.mpd}
format-online-underline		=	 ${moducolors.mpd}
format-padding 				=	 10
format-offline 				=	 <label-offline>

; label correction
label-song 					=	 "%title%"
label-song-ellipsis 		=	 true
label-song-width			= 	25
label-time 					= 	%elapsed% / %total%
label-offline 				=	"MPD is offline"
; icons
icon-play 					=	 
icon-pause 					=	 
icon-stop 					=	 
icon-prev 					=	 
icon-next 					=	 
icon-seekb 					=	 
icon-seekf 					=	 
icon-random 				=	 
icon-repeat 				=	 
; Available tags:
;   <label-song><label-time></ar-progress><icon-random>
;   <icon-repeat><icon-single>
;   <icon-consume><icon-prev><icon-stop><icon-play>
;   <icon-pause><icon-next><icon-seekb><icon-seekf>
; Available tokens:
;   %artist%%album-artist%%album%%date%%title%
; Available tokens:
;   %elapsed%
;   %total%
; }}}

; pulse {{{
[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
sink = mainAudio
interval = 5
; Available tags: {label,ramp,bar}-volume
format-volume = <ramp-volume> <label-volume>
format-volume-padding = ${layout.module-padding}
format-muted = <label-muted>
format-muted-prefix = 
; Available tokens:
;   %percentage% (default)
label-muted = Muted
label-muted-padding = ${layout.module-padding}

; Only applies if <ramp-volume> is used
ramp-volume-foreground = ${moducolors.pulseaudio}
ramp-volume-0 = 
ramp-volume-1 = 
; that icon needs to be fixed tho
ramp-volume-2 = 奔
ramp-volume-3 = 墳
ramp-volume-4 = 

; }}}

; keyboard{{{
[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format =  <label-layout>
format-prefix = 
format-prefix-padding-right = 2;
format-prefix-foreground = ${moducolors.keyboard}
format-padding = ${layout.module-padding}
label-layout = %layout%

; }}}

; title{{{
[module/title]
type 				= internal/xwindow
format 				= <label>
label 				= %title%
label-maxlen 		= 40
label-empty 		= Arch Linux
format-padding 		= ${layout.module-padding}
format-foreground 	= ${moducolors.title}
format-underline	= ${moducolors.title}

; }}}

; university{{{

[module/currentcourse]
type = custom/script
tail = true
exec = cat /tmp/current-course
click-left = 'notify-send `~/code/scripts/uni/countdown.py`'
interval = 10

[module/coursecalendar]
type = custom/script
exec = ~/code/scripts/uni/countdown.py
tail = true
interval = 60

;}}}

; reddit{{{
[module/reddit]
type = custom/script
interval = 60
exec = ~/.config/polybar/scripts/notification-reddit.sh
click-left = "brave https://www.reddit.com"

format = <label>
format-prefix = 
format-prefix-foreground = ${moducolors.keyboard}
; }}}

; eyestrain{{{
[module/safeeyes]
type = custom/script
exec = safeeyes --status | awk -v date=`date '+%I:%M'` -F" " '{print date , $4}'
click-left = safeeyes --disable
click-right = safeeyes --enable
interval = 1

format-underline = ${moducolors.keyboard}
format-prefix = " 祥 "
format-prefix-foreground = ${moducolors.keyboard}

; }}}

; github {{{
[module/github]
type = custom/script
exec = sh ~/.config/polybar/scripts/notification-github.sh
click-left = brave "https://github.com"
interval = 60


format = <label>
format-prefix = 
format-prefix-foreground = ${moducolors.keyboard}
; }}}
