; Customization by Lamprinos Chatziioannou

include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

; General {{{
[global/wm]
margin-top 				= 8
margin-bottom			= 2

[bar/template]
monitor-strict 			= 	false
override-redirect 		= 	false
fixed-center 			= 	false
offset-y 				= 	4
underline-size 			= 	2
module-margin 			= 	1
height 					= 	20
radius 					= 	8
enable-ipc 				=	false

; colors
background 				= ${std.bg}
foreground 				= ${std.fg}

font-0 = "Iosevka Nerd Font:style=Medium:size=9"

; }}}

; Bars {{{
[bar/left]
inherit 				= 	bar/template
modules-center 			= 	bspwm
width					=	15%
offset-x				=	5%


[bar/middle]
inherit 				= 	bar/template
modules-center			= 	currentcourse coursecalendar
width					= 	40%
offset-x				=	30%

[bar/right]
inherit 				= 	bar/template
modules-center 			= 	keyboard mpd pulseaudio date
width					=	15%
offset-x				=	80%

;}}}

; layout{{{
[layout]
locale 					=	 en_US.UTF-8
dim-value 				=	 0.4
module-padding 			=	 2
bspwm-padding			=	 2
wm-name 				=	 bspwm
wm-restack 				=	 bspwm
;}}}

; Settings{{{
[settings]
throttle-output 		= 5
throttle-output-for 	= 10
throttle-input-for 		= 30
screenchange-reload 	= false
compositing-background 	= source
compositing-foreground 	= over
compositing-overline 	= over
compositing-underline 	= over
compositing-border 		= over
;}}}
