; Customization by Lamprinos Chatziioannou

include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

; template {{{
[bar/template]
margin-top 				= 	8
monitor					= 	HDMI-0
margin-bottom			= 	2
monitor-strict 			= 	false
override-redirect 		= 	false
fixed-center 			= 	false
offset-y 				= 	4
underline-size 			= 	2
module-margin 			= 	1
height 					= 	30
radius 					= 	10
padding					=	5
enable-ipc 				=	true

; colors
background 				= ${std.bg}
foreground 				= ${std.fg}

font-0 = "Iosevka Nerd Font:style=Medium:size=9"
; }}}

; Tray {{{
;tray-position = right
;tray-padding  = 10
;tray-background =
;tray-offset-{x,y}
; }}}

; Bars {{{
[bar/left]
inherit 				= 	bar/template
modules-center			= 	desktops
width					=	15%
offset-x				=	25%

[bar/right]
inherit 				= 	bar/template
modules-center 			= 	keyboard pulseaudio github reddit safeeyes 
width					=	15%
offset-x				=	60%

[bar/middle]
inherit 				= 	bar/template
modules-center			= 	currentcourse 
width					=	14%
offset-x				=	43%
;}}}

; layout{{{
[layout]
locale 					=	 en_US.UTF-8
dim-value 				=	 0.4
module-padding 			=	 2
bspwm-padding			=	 2
wm-name 				=	 bspwm
wm-restack 				=	 bspwm
;}}}

; Settings{{{
[settings]
throttle-output 		= 5
throttle-output-for 	= 10
throttle-input-for 		= 30
screenchange-reload 	= false
compositing-background 	= source
compositing-foreground 	= over
compositing-overline 	= over
compositing-underline 	= over
compositing-border 		= over
;}}}
